### ISSUE TITLE
Sconto 1000€

### ISSUE THREAD

**Issue by CesconMatteo** [CesconMatteo/MTSS-Assignment2#5]
Se l’importo totale degli articoli supera i 1000 euro viene fatto uno sconto del 10% sul totale.

**Comment by LucaBru** [comment]
Commit di riferimento 035a341c2f2dbfd1c51a0460e2e31a3ca06b8f8d
Da titolo del commit si nota come l'errore di battitura #close 5 (invece di close #5) non chiuda la issue corrente.
